### ISSUE TITLE
Pihole - Version 6 Support

### ISSUE THREAD

**Issue by FurkanVG** [PinchToDebug/Pihole-Tray#1]
Hey,

i think this only supports V5?

V6 is using different API paths and logic, so it doesnt work on my V6.

**Comment by PinchToDebug** [comment]
Hi, It only support V5 at the moment!

**Comment by FurkanVG** [comment]
:( im sad. Cool tool! Tho i would consider adding V6 Support, since it will be slowly out of development and will go to prod (tho this will prb still take few months prb)

**Comment by PinchToDebug** [comment]
I will support V6 in the future! :)

**Comment by PinchToDebug** [comment]
Feature has been added.
