### ISSUE TITLE
"Sources" element data issues

### ISSUE THREAD

**Issue by lexcyn** [PinchToDebug/Pihole-Tray#2]
Issue: When enabling the "sources" element field, other fields like DNS Routes are left empty. If you disable sources, the other fields work fine.

Example shown in the screen recording attached.

https://github.com/user-attachments/assets/05b7e67a-dc2b-47bb-b5ea-0017b2861ad4

**Comment by PinchToDebug** [comment]
Could you close the app, and send me a screenshot of Computer\HKEY_CURRENT_USER\Software\Pihole_Tray in the registries?

**Comment by lexcyn** [comment]
Here you go:
![image](https://github.com/user-attachments/assets/50d2557a-4fa0-4c0a-b533-5b4be1217e05)

**Comment by PinchToDebug** [comment]
If you delete the ones with the "TS" at the end, and open up the app, does it solve the issue?

**Comment by lexcyn** [comment]
> If you delete the ones with the "TS" at the end, and open up the app, does it solve the issue?

I tried that but now the app won't open. I had to disable the elements again and then when it launched, only leave Sources disabled, and now it launches normally. But I see the registry values re-created.

**Comment by PinchToDebug** [comment]
The main problem is that I couldn't reproduce the issue. I also see that you are using an insider version of Windows and it might be the source of the problem, but I'm clueless to be fair. If you can try it on a different device and report back I would appreciate that.

**Comment by lexcyn** [comment]
> The main problem is that I couldn't reproduce the issue. I also see that you are using an insider version of Windows and it might be the source of the problem, but I'm clueless to be fair. If you can try it on a different device and report back I would appreciate that.

I tried on my work system which is Windows 11 23H2 and I am experiencing the same issue unfortunately :(

**Comment by PinchToDebug** [comment]
I will look into it.

**Comment by PinchToDebug** [comment]
I tested it on Windows 11 22H2, and 23H2 and i still couldn't reproduce the issue that you are having.
Please try to change the lines in MainWindow.xaml.cs from:

```c#
                    if ((bool)RecentBlocksTS.IsChecked) await new AllQueriesLoader().LoadAsync(BlockHistoryItemsControl, queries_data);
                    if ((bool)SourcesTS.IsChecked) await new QuerySourcesLoader().LoadAsync(SourcesItemsControl, topSources);
                    if ((bool)DNSRoutesTS.IsChecked) await new ForwardDestinationsLoader().LoadAsync(DnsRoutesGrid, forward_destinations);
                    if ((bool)QueryTS.IsChecked) await new QueryTypesLoader().LoadAsync(QueryTypesGrid, querytypes);
``` 

to:
```c#
   int delayTest = 500;
   
   await Task.Delay(delayTest);
   if ((bool)RecentBlocksTS.IsChecked) await new AllQueriesLoader().LoadAsync(BlockHistoryItemsControl, queries_data);
   await Task.Delay(delayTest);
   if ((bool)SourcesTS.IsChecked) await new QuerySourcesLoader().LoadAsync(SourcesItemsControl, topSources);
   await Task.Delay(delayTest);
   if ((bool)DNSRoutesTS.IsChecked) await new ForwardDestinationsLoader().LoadAsync(DnsRoutesGrid, forward_destinations);
   await Task.Delay(delayTest);
   if ((bool)QueryTS.IsChecked) await new QueryTypesLoader().LoadAsync(QueryTypesGrid, querytypes);
   await Task.Delay(delayTest);
``` 

The issue you're experiencing seems network-related. If it works, please try with lower numbers like 100, 50, 20, etc., and report back on the results.

**Comment by PinchToDebug** [comment]
I tested it on Windows 11 22H2, and 23H2 and I still couldn't reproduce the issue that you are having.
Please modify from line 499 in **MainWindow.xaml.cs**:

```c#
                    if ((bool)RecentBlocksTS.IsChecked) await new AllQueriesLoader().LoadAsync(BlockHistoryItemsControl, queries_data);
                    if ((bool)SourcesTS.IsChecked) await new QuerySourcesLoader().LoadAsync(SourcesItemsControl, topSources);
                    if ((bool)DNSRoutesTS.IsChecked) await new ForwardDestinationsLoader().LoadAsync(DnsRoutesGrid, forward_destinations);
                    if ((bool)QueryTS.IsChecked) await new QueryTypesLoader().LoadAsync(QueryTypesGrid, querytypes);
``` 

to:
```c#
   int delayTest = 500;
   
   await Task.Delay(delayTest);
   if ((bool)RecentBlocksTS.IsChecked) await new AllQueriesLoader().LoadAsync(BlockHistoryItemsControl, queries_data);
   await Task.Delay(delayTest);
   if ((bool)SourcesTS.IsChecked) await new QuerySourcesLoader().LoadAsync(SourcesItemsControl, topSources);
   await Task.Delay(delayTest);
   if ((bool)DNSRoutesTS.IsChecked) await new ForwardDestinationsLoader().LoadAsync(DnsRoutesGrid, forward_destinations);
   await Task.Delay(delayTest);
   if ((bool)QueryTS.IsChecked) await new QueryTypesLoader().LoadAsync(QueryTypesGrid, querytypes);
   await Task.Delay(delayTest);
``` 

The issue you're experiencing seems network-related. If it works, please try with lower numbers like 100, 50, 20, etc., and report back on the results.

**Comment by lexcyn** [comment]
Sorry I am not really a programmer (haha) so do you need me to edit this and recompile the app? Are you using Visual Studio?

**Comment by PinchToDebug** [comment]
Yes I'm using VS.
I released a newer version please check that out, I hope it got resolved!

**Comment by Tgo1014** [comment]
This new version fixed it for me! Thanks! Hopefully it fixes for the others as well.

**Comment by lexcyn** [comment]
> Yes I'm using VS. I released a newer version please check that out, I hope it got resolved!

Downloaded the new version and it fixed the Sources bug :) Thanks!!
