### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by hspindel** [PinchToDebug/Pihole-Tray#4]
Readme says "easy installation".  Can you please provide installation instructions?

**Comment by PinchToDebug** [comment]
When you open the application you will see this:
![image](https://github.com/user-attachments/assets/20332e56-0ad4-433f-a70c-6d0cb7eb1f40)

- First field: Give any name you would like to give it, it won't be seen unless you have more than 1 instances

- Second field: The text you see on the image is an example. If you have the Pi-hole on your local network and your device is using it as the DNS provider then just type that in what you see there, or if it's not set as the DNS server on your device, then type "http://IPADDRESS/admin/api.php" where the IPADDRESS is your Pi-hole's IP.

- Third field: There's a link under it you can use that or change the pi.hole to the Pi-hole's IP.

**Comment by hspindel** [comment]
You described the configuration needed for pihole-tray.  I was intending to ask about how to install pihole-tray from the zip file I downloaded so I can get to the configuration pages you described.

I'm not seeing an installer or anything that looks like an executable.

Thank you.

**Comment by PinchToDebug** [comment]
There's no installer for it, just source code and executable.
https://github.com/PinchToDebug/Pihole-Tray/releases
![image](https://github.com/user-attachments/assets/139d25b6-844e-417e-bd5f-07cddd98bdaf)

**Comment by hspindel** [comment]
Thank you.  I was unable to find the pihole_tray.exe file before.
