### ISSUE TITLE
App Crashes immediately after launch

### ISSUE THREAD

**Issue by EmpokNor47** [PinchToDebug/Pihole-Tray#5]
App Crashes immediately.  Icon shows on system tray them disappears.

Event Viewer Log:

Source:        Application Error
Date:          8/23/2024 6:25:19 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      ******
Description:
Faulting application name: Pihole_Tray.exe, version: 0.1.0.0, time stamp: 0x65410000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.4717, time stamp: 0x16b0a901
Exception code: 0xc000041d
Fault offset: 0x000000000003b699
Faulting process id: 0x502c
Faulting application start time: 0x01daf54f219d3cfb
Faulting application path: C:\Users\******\Downloads\Pihole_Tray.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: e3155e39-1827-4ab6-a41d-692ccffc592e
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-08-23T11:25:19.4417256Z" />
    <EventRecordID>3864</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>******</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Pihole_Tray.exe</Data>
    <Data>0.1.0.0</Data>
    <Data>65410000</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.4717</Data>
    <Data>16b0a901</Data>
    <Data>c000041d</Data>
    <Data>000000000003b699</Data>
    <Data>502c</Data>
    <Data>01daf54f219d3cfb</Data>
    <Data>C:\Users\******\Downloads\Pihole_Tray.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>e3155e39-1827-4ab6-a41d-692ccffc592e</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by PinchToDebug** [comment]
I will push an update soon, that will help debug these problems.

**Comment by PinchToDebug** [comment]
New version released, problem should be solved.

**Comment by EmpokNor47** [comment]
Downloaded 0.1.2,  still crashes on launch

**Comment by PinchToDebug** [comment]
Are you on Windows 10?

**Comment by EmpokNor47** [comment]
Yes

**Comment by PinchToDebug** [comment]
Do you have VS and able to run the program in debug mode?

**Comment by PinchToDebug** [comment]
Please check out the latest version, I believe it got fixed.

**Comment by EmpokNor47** [comment]
This cleared it, thanks!
