### ISSUE TITLE
Easy  Setup

### ISSUE THREAD

**Issue by Hacnstein** [PinchToDebug/Pihole-Tray#8]
In the setup after adding the API key I'm getting can't reach host, maybe DNS..  Yet the link in that window will go right to the pihole?  Typing pi.hole/admin in the browser goes right to the interface too.  What am I missing?

**Comment by PinchToDebug** [comment]
Please check this: https://github.com/PinchToDebug/Pihole-Tray/issues/4

**Comment by Hacnstein** [comment]
Ok, I tried to enter the ip in that field that looks like it is populated with the URL and I couldn't just edit the pi.hole to my IP, didn't try clicking in the front of that field to re-type the whole URL..bad design or bad user?  But thanks for the link, it is working!

**Comment by PinchToDebug** [comment]
You have to enter the link the way it is because some people use it on other addresses not just on local Pi-holes. I will probably remove the placeholder text because I see how it can be confusing. Thanks for reminding me!

**Comment by PinchToDebug** [comment]
You have to enter the link as it is, because this program allows you to access Pi-hole on non-local networks and without setting the DNS on the device running the program. I'll likely remove the placeholder text as I see how it can be confusing. Thanks for the reminder!
