### ISSUE TITLE
Right Click Menu - Pi.hole shortcut seems hardcoded

### ISSUE THREAD

**Issue by Chouhada** [PinchToDebug/Pihole-Tray#9]
Hi
Thanks for the app.

I have successfully installed and configure the app, with stats working, along with disable/enabling.
However, the right click menu on the app in the tray seems to have http://pi.hole has a hardcoded value, or has not updated:
![image](https://github.com/user-attachments/assets/1ff642a8-fce8-4b0e-8ddd-d5d4e7711329)

Clicking this takes me to http://pi.hole, but this is not where my pihole instance is.

It would be great if this shortcut updated to the correct URL, based on the URL given for the API URL.

**Comment by PinchToDebug** [comment]
Hi, yes it is hardcoded at the moment. I will release a QOL update soon!

**Comment by PinchToDebug** [comment]
Fixed.
